<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Seeder;

class NBATeamsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Seeds all 30 NBA teams with official logos from NBA CDN
     */
    public function run(): void
    {
        $teams = [
            // Atlantic Division
            [
                'name' => 'Boston Celtics',
                'abbreviation' => 'BOS',
                'location' => 'Boston',
                'nickname' => 'Celtics',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/celtics/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612738/primary/L/logo.svg',
                'color' => '#007A33',
            ],
            [
                'name' => 'Brooklyn Nets',
                'abbreviation' => 'BKN',
                'location' => 'Brooklyn',
                'nickname' => 'Nets',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/nets/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg',
                'color' => '#000000',
            ],
            [
                'name' => 'New York Knicks',
                'abbreviation' => 'NYK',
                'location' => 'New York',
                'nickname' => 'Knicks',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/knicks/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg',
                'color' => '#006BB6',
            ],
            [
                'name' => 'Philadelphia 76ers',
                'abbreviation' => 'PHI',
                'location' => 'Philadelphia',
                'nickname' => '76ers',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/sixers/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg',
                'color' => '#006BB6',
            ],
            [
                'name' => 'Toronto Raptors',
                'abbreviation' => 'TOR',
                'location' => 'Toronto',
                'nickname' => 'Raptors',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/raptors/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg',
                'color' => '#CE1141',
            ],

            // Central Division
            [
                'name' => 'Chicago Bulls',
                'abbreviation' => 'CHI',
                'location' => 'Chicago',
                'nickname' => 'Bulls',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/bulls/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg',
                'color' => '#CE1141',
            ],
            [
                'name' => 'Cleveland Cavaliers',
                'abbreviation' => 'CLE',
                'location' => 'Cleveland',
                'nickname' => 'Cavaliers',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/cavaliers/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg',
                'color' => '#860038',
            ],
            [
                'name' => 'Detroit Pistons',
                'abbreviation' => 'DET',
                'location' => 'Detroit',
                'nickname' => 'Pistons',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/pistons/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612765/primary/L/logo.svg',
                'color' => '#C8102E',
            ],
            [
                'name' => 'Indiana Pacers',
                'abbreviation' => 'IND',
                'location' => 'Indiana',
                'nickname' => 'Pacers',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/pacers/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612754/primary/L/logo.svg',
                'color' => '#002D62',
            ],
            [
                'name' => 'Milwaukee Bucks',
                'abbreviation' => 'MIL',
                'location' => 'Milwaukee',
                'nickname' => 'Bucks',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/bucks/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612749/primary/L/logo.svg',
                'color' => '#00471B',
            ],

            // Southeast Division
            [
                'name' => 'Atlanta Hawks',
                'abbreviation' => 'ATL',
                'location' => 'Atlanta',
                'nickname' => 'Hawks',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/hawks/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612737/primary/L/logo.svg',
                'color' => '#E03A3E',
            ],
            [
                'name' => 'Charlotte Hornets',
                'abbreviation' => 'CHA',
                'location' => 'Charlotte',
                'nickname' => 'Hornets',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/hornets/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612766/primary/L/logo.svg',
                'color' => '#1D1160',
            ],
            [
                'name' => 'Miami Heat',
                'abbreviation' => 'MIA',
                'location' => 'Miami',
                'nickname' => 'Heat',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/heat/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg',
                'color' => '#98002E',
            ],
            [
                'name' => 'Orlando Magic',
                'abbreviation' => 'ORL',
                'location' => 'Orlando',
                'nickname' => 'Magic',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/magic/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612753/primary/L/logo.svg',
                'color' => '#0077C0',
            ],
            [
                'name' => 'Washington Wizards',
                'abbreviation' => 'WAS',
                'location' => 'Washington',
                'nickname' => 'Wizards',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/wizards/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612764/primary/L/logo.svg',
                'color' => '#002B5C',
            ],

            // Northwest Division
            [
                'name' => 'Denver Nuggets',
                'abbreviation' => 'DEN',
                'location' => 'Denver',
                'nickname' => 'Nuggets',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/nuggets/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612743/primary/L/logo.svg',
                'color' => '#0E2240',
            ],
            [
                'name' => 'Minnesota Timberwolves',
                'abbreviation' => 'MIN',
                'location' => 'Minnesota',
                'nickname' => 'Timberwolves',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/timberwolves/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612750/primary/L/logo.svg',
                'color' => '#0C2340',
            ],
            [
                'name' => 'Oklahoma City Thunder',
                'abbreviation' => 'OKC',
                'location' => 'Oklahoma City',
                'nickname' => 'Thunder',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/thunder/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612760/primary/L/logo.svg',
                'color' => '#007AC1',
            ],
            [
                'name' => 'Portland Trail Blazers',
                'abbreviation' => 'POR',
                'location' => 'Portland',
                'nickname' => 'Trail Blazers',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/blazers/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612757/primary/L/logo.svg',
                'color' => '#E03A3E',
            ],
            [
                'name' => 'Utah Jazz',
                'abbreviation' => 'UTA',
                'location' => 'Utah',
                'nickname' => 'Jazz',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/jazz/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612762/primary/L/logo.svg',
                'color' => '#002B5C',
            ],

            // Pacific Division
            [
                'name' => 'Golden State Warriors',
                'abbreviation' => 'GSW',
                'location' => 'Golden State',
                'nickname' => 'Warriors',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/warriors/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg',
                'color' => '#1D428A',
            ],
            [
                'name' => 'LA Clippers',
                'abbreviation' => 'LAC',
                'location' => 'LA',
                'nickname' => 'Clippers',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/clippers/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612746/primary/L/logo.svg',
                'color' => '#C8102E',
            ],
            [
                'name' => 'Los Angeles Lakers',
                'abbreviation' => 'LAL',
                'location' => 'Los Angeles',
                'nickname' => 'Lakers',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/lakers/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg',
                'color' => '#552583',
            ],
            [
                'name' => 'Phoenix Suns',
                'abbreviation' => 'PHX',
                'location' => 'Phoenix',
                'nickname' => 'Suns',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/suns/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg',
                'color' => '#1D1160',
            ],
            [
                'name' => 'Sacramento Kings',
                'abbreviation' => 'SAC',
                'location' => 'Sacramento',
                'nickname' => 'Kings',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/kings/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612758/primary/L/logo.svg',
                'color' => '#5A2D81',
            ],

            // Southwest Division
            [
                'name' => 'Dallas Mavericks',
                'abbreviation' => 'DAL',
                'location' => 'Dallas',
                'nickname' => 'Mavericks',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/mavericks/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612742/primary/L/logo.svg',
                'color' => '#00538C',
            ],
            [
                'name' => 'Houston Rockets',
                'abbreviation' => 'HOU',
                'location' => 'Houston',
                'nickname' => 'Rockets',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/rockets/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612745/primary/L/logo.svg',
                'color' => '#CE1141',
            ],
            [
                'name' => 'Memphis Grizzlies',
                'abbreviation' => 'MEM',
                'location' => 'Memphis',
                'nickname' => 'Grizzlies',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/grizzlies/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612763/primary/L/logo.svg',
                'color' => '#5D76A9',
            ],
            [
                'name' => 'New Orleans Pelicans',
                'abbreviation' => 'NOP',
                'location' => 'New Orleans',
                'nickname' => 'Pelicans',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/pelicans/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612740/primary/L/logo.svg',
                'color' => '#0C2340',
            ],
            [
                'name' => 'San Antonio Spurs',
                'abbreviation' => 'SAS',
                'location' => 'San Antonio',
                'nickname' => 'Spurs',
                'league' => 'NBA',
                'url' => 'https://www.nba.com/spurs/',
                'logo_url' => 'https://cdn.nba.com/logos/nba/1610612759/primary/L/logo.svg',
                'color' => '#C4CED4',
            ],
        ];

        foreach ($teams as $team) {
            Team::create($team);
        }
    }
}
